### ISSUE TITLE
Crash while resolving large number of conflicts

### ISSUE THREAD

**Issue by else** [mkchoi212/fac#46]
```
 [w,a,s,d,e,?] >> panic: runtime error: slice bounds out of range

goroutine 337 [running]:
github.com/nsf/termbox-go.PollEvent(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /Users/else/go/src/github.com/nsf/termbox-go/api.go:348 +0x8d4
github.com/jroimartin/gocui.(*Gui).MainLoop.func1(0xc00020a090)
        /Users/else/go/src/github.com/jroimartin/gocui/gui.go:354 +0x30
created by github.com/jroimartin/gocui.(*Gui).MainLoop
        /Users/else/go/src/github.com/jroimartin/gocui/gui.go:352 +0x6e
$ fac -v
fac 2.0
```

**Comment by mkchoi212** [comment]
Could you provide the file you were attempting to fix by any chance?

**Comment by else** [comment]
Unfortunately this is not possible, and also not easy to find out, because the list of files on the right side is larger than the window (or is there a scroll possibility?)

**Comment by mkchoi212** [comment]
closing for now
