### ISSUE TITLE
panic: runtime error: slice bounds out of range [1:0]

### ISSUE THREAD

**Issue by abitrolly** [mkchoi212/fac#50]
I tried to rebase https://github.com/terraform-providers/terraform-provider-github/pull/96 on top of https://github.com/terraform-providers/terraform-provider-github/pull/108/files and got this.

First I tried to see the result of previous conflict resolution using `[p]`, but it looked like result was not saved (I use `e` and `a` for each change). I edited conflict again, and then the green line appeared at the bottom. I edited one or more conflict before the crash happened.
```

┌─c2463a8d064e5b683571835fea1bb9580ef9cebc  (Incoming Version)──────────────────────────────────────────────────────────────────────────│✔ github/resource_github_reposi│
│func resourceGithubTeamMembershipRead(d *schema.ResourceData, meta interface{}) error {                                                │✔ github/resource_github_reposi│
│ client := meta.(*Owner).client                                                                                                        │✔ github/resource_github_reposi│
│ t, n := parseTwoPartID(d.Id())                                                                                                        │✔ github/resource_github_reposi│
│>>>>>>> c2463a8d064e5b683571835fea1bb9580ef9cebc                                                                                       │✔ github/resource_github_reposi│
│                                                                                                                                       │-> 20. github/resource_github_t│
│                                                                                                                                       │21. github/resource_github_team│
│                                                                                                                                       │22. github/resource_github_team│
│                                                                                                                                       │23. github/resource_github_team│
│                                                                                                                                       │✔ github/resource_github_team_r│
│                                                                                                                                       │                               │
│                                                                                                                                       │                               │
│                                                                                                                                       │                               │
│                                                                                                                                       │                               │
│                                                                                                                                       │                               │
│                                                                                                                                       │                               │
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────└───────────────────────────────┘
 [w,a,s,d,e,?] >> panic: runtime error: slice bounds out of range [1:0]

goroutine 274 [running]:
github.com/nsf/termbox-go.PollEvent(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/anatoli/go/src/github.com/nsf/termbox-go/api.go:356 +0x905
github.com/jroimartin/gocui.(*Gui).MainLoop.func1(0xc0000fc480)
	/home/anatoli/go/src/github.com/jroimartin/gocui/gui.go:354 +0x30
created by github.com/jroimartin/gocui.(*Gui).MainLoop
	/home/anatoli/go/src/github.com/jroimartin/gocui/gui.go:352 +0x57
```

**Comment by abitrolly** [comment]
Could be connected to me pressing enter at random moments or other non-expected keys (switching to and from `vim` is confusing).
